### ISSUE TITLE
Warnings about the v.112 multiple entities condition

### ISSUE THREAD

**Issue by febalci** [hassio-addons/addon-vscode#119]
On HA v.112, the new property which allows to use multiple entities and states in YAML configurations causes a warning/error:

```
  condition:
    - condition: state
      entity_id: 
        - binary_sensor.xiaomi_motion_sensor_a
        - binary_sensor.xiaomi_motion_sensor_b
      state: 'off'
```
gives out: 'Incorrect type. Expected "string"' on 'state: 'off'' line.
