### ISSUE TITLE
causing core.restore_state not to update upon HA restart

### ISSUE THREAD

**Issue by xenz698** [hassio-addons/addon-vscode#124]
# Problem/Motivation

> Original started with Input_* won't restore state after HA restart. After days of isolation and narrow down, I reach the bare minimum config and I can reproduce the problem 100%.  If I have a browser tab with VScode open, HA won't do the final save state to core.restore_state upon restart.  if the tab with VScode was closed. core.restore_state updated, thus input_* state will be restore upon restart.

## Expected behavior

> Expecting VScode won't affect HA final save state upon restart

## Actual behavior

> For whatever reason, with VSCode open, from any browser or any computer. HA won't save state upon restart (the final save state), NOTE: the regular 15min state save works OK. only affect the final state save just before restart

> I always have 4 browser tabs open. 1 is the HA Overview, 1 is the Developers State or Template view 1 is the HA Server Control view and 1 is always VScode. so I just switch between tabs for scripting, check states/tempalte, seeing the UI and restarting HA.  All start with input_text not surviving restart. then noticed all input_* entites.  Learnt that survive state has nothing to do with database, but solely save to the core.restore_state file.  Enabling DEBUG mode which gave too much noise on the log, start stripping down components in the configuration.yaml, integrations and finally stripping down Add-ons and found out VSCode cause the issue.    With pretty much close to empty configuration.yaml, add-ons and integration. now reading the DEBUG log is manageable. 

## Steps to reproduce

> 1. Strip down configuration to bare minimum. uninstall all Add-on except VSCode. remove all removable integration.
> 2. set the input_text.test_saving state to something.   
> 3. Open a browser tab and open up VScode, either from side bar or open Supervisor > VScode Addon > open webui .  and leave this VScode tab running
> 4. Open another browser tab and goto HA > Configuration > Server Control > Server Management > Restart
> 5. check input_text.test_saving value.
> Value won't be save no matter how many time you set value and restart
> now close the VScode browser tab, repeat step #2, #4 and #5
> Value will be saved and survive restart

```
homeassistant:
  auth_providers:
  - type: homeassistant

frontend:
  themes: !include themes.yaml

http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

input_boolean:
  test_saving:

input_datetime:
  test_saving:
    has_time: true
    has_date: true

input_number:
  test_saving:
    min: 1
    max: 50

input_select:
  test_saving:
    options:
    - One
    - Two

input_text:
  test_saving:

logger:
  default: debug

lovelace:
  mode: yaml
```
![no addons](https://user-images.githubusercontent.com/29969334/89096761-cbb97580-d38d-11ea-9bff-ea8d79ef1994.png)
![bare integration](https://user-images.githubusercontent.com/29969334/89096762-ce1bcf80-d38d-11ea-849c-51b3c95d79bb.png)

## Proposed changes

> Sorry, I do not. 

## Addtional Info. 

> you can see my original troubleshooting on home assistant core issue #[38215 ](https://github.com/home-assistant/core/issues/38215)

**Comment by xenz698** [comment]
I can 100% confirm my finding.
- Create a new VM
- installed HA 0.113.3
- install Visual Studio Code Add on
- change configuration.yaml by adding 
```
input_text:
  test_saving:
```

so the configuration.yaml is the default one plus input_text

```
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

input_text:
  test_saving:
```
- using Single browser tab, open HA, change input_text value to "1st try" , restart HA
- input_text value showing "1st try" survive restart
- open Visual Studio Code on an extra tab, and keep this tab open, use the 1st tab to change input_text value to "2nd try VScode open", restart HA
- new input_text value didn't survive restart, input_text value shown is "1st try"
