### ISSUE TITLE
String does not match the pattern of "^sensor\.(?!_)[\da-z_]+(?<!_)\s?(?:,\s?sensor\.(?!_)[\da-z_]+(?<!_))*$".

### ISSUE THREAD

**Issue by wilfredsmit** [hassio-addons/addon-vscode#127]
# Problem/Motivation
I have an issue in an automation. At the third line of the trigger I get the following error in red:

`String does not match the pattern of "^sensor\.(?!_)[\da-z_]+(?<!_)\s?(?:,\s?sensor\.(?!_)[\da-z_]+(?<!_))*$".`

<img width="1165" alt="Schermafbeelding 2020-08-10 om 15 42 50" src="https://user-images.githubusercontent.com/31591364/89788979-40c04400-db20-11ea-8bcc-3a87576d40f2.png">

But for as I can see, there is nothing wrong with the line **entity_id: light.corridor_wall**

```
---
alias: corridor_turn_off_light_after_power_cycle
initial_state: true

trigger:
  platform: numeric_state
  entity_id: light.corridor_wall
  value_template: '{{ state.attributes.brightness | default(0) | int }}'
  above: 253

action:
  service: light.turn_off
  data: 
    entity_id: light.corridor_wall
```
It is quiet annoying that VSCode says there is a fault in one of my YAML files.

## Expected behavior
Not to show this error line.

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

I'm on add-on version 2.4.0. of VSCode and I'm on Home Assistant 0.113.3.
