### ISSUE TITLE
VSCode reports an error on the icon in the MQTT Light config

### ISSUE THREAD

**Issue by stickpin** [hassio-addons/addon-vscode#235]
# Problem/Motivation

VSCode reports an error on the icon in the MQTT Light config.

<img width="573" alt="Screenshot 2021-04-15 at 15 59 25" src="https://user-images.githubusercontent.com/630000/114881787-9cf00c00-9e03-11eb-9507-58a082b67d06.png">

Based on the documentation it's a completely valid configuration variable.
https://www.home-assistant.io/integrations/light.mqtt/

## Expected behavior

Should not report an error

## Actual behavior

Reporting an error

## Steps to reproduce

Add the following config to the configuration.yaml:
```
light:
  - platform: mqtt
    schema: json
    name: "My light ZGroup"
    command_topic: "zigbee2mqtt/My light ZGroup/set"
    state_topic: "zigbee2mqtt/My light ZGroup"
    color_temp: true
    brightness: true
    rgb: true
    icon: mdi:lightbulb-group
```

Please let me know if you need more info.

Thanks in advance!
