### ISSUE TITLE
Invalid automation-schema error when adding context to an event trigger

### ISSUE THREAD

**Issue by grillp** [hassio-addons/addon-vscode#278]
# Problem/Motivation

> The schema for the automation.yaml file does not include 'context:' under "trigger > platform: event".

## Expected behavior

> In the UI you can add context to a trigger (e.g. which user generate the event) to filter the automation to run only for a specific user. This generates a valid `automation.yaml` file that works as expected, but the schema validation in  vs-code addon shows an error at the 'context:' entry:

`Property context is not allowed.yaml-schema: http://schemas.home-assistant.io/integration-automation`

## Actual behavior

> Error shows in vs-code 

## Steps to reproduce

>  Create an automation with an event trigger (e.g. ios.action_fired) and under `Limit to events triggered by` select a user to set the context. Edit the `automations.yaml` file in vs-code to see the schema error.

e.g:

```
- id: '1619006716292'
  alias: 'iOS: Fred's light'
  description: Action to turn on Freds's bedside light from iOS
  trigger:
  - platform: event
    event_type: ios.action_fired
    event_data:
      actionName: bedside_light
    context:
      user_id:
      - 2cddf860e78d47ff9345685fcf837aae
```

## Proposed changes

Add the additional schema definition to allow context.
