### ISSUE TITLE
Template switch marked with error

### ISSUE THREAD

**Issue by dunkelz** [hassio-addons/addon-vscode#382]
# Problem/Motivation

> When the [Template Switch](https://www.home-assistant.io/integrations/switch.template/) is split into multiple files the linter shows error messages:
_Property platform is not allowed.
Property name is not allowed._

## Expected behavior

> No error message displayed

## Actual behavior

> Error message is displayed in the editor, the switch itself however works fine.

## Steps to reproduce

Studio Code Server v4.1.0

1. Add to configuration.yaml the line to include switches from external files
`switch: !include_dir_merge_list entity/switch/`
2. Create a config file in entity/switch/ (skylight.yaml)
3. Insert code for a template switch
```
- platform: template
  switches:
    skylight:
      value_template: "{{ is_state('sensor.skylight', 'on') }}"
      turn_on:
        service: switch.turn_on
        target:
          entity_id: switch.skylight_open
      turn_off:
        service: switch.turn_off
        target:
          entity_id: switch.skylight_close
```

![image](https://user-images.githubusercontent.com/23629994/150687703-e1eef552-3b91-413c-b2b5-b99970a02919.png)
