### ISSUE TITLE
Studio Code Server - Erroneous error messages

### ISSUE THREAD

**Issue by MilesAheadToo** [hassio-addons/addon-vscode#393]
# Problem/Motivation

> After updating to v4.1.0 I am getting incorrect error messages when viewing YAML files that work correctly, conform to formatting conventions, and did not not display errors before.

## Expected behavior

> That no errors would be shown

## Actual behavior

> SCS reports multiple errors 

## Steps to reproduce

> Create a `sensors.yaml` file that is referenced in `configuration.yaml` as below
`sensor: !include sensors.yaml`

The following code in the sensors.yaml file will generate errors on SCS
```
- platform: systemmonitor
  resources:
    - type: disk_use_percent
    - type: memory_use_percent
    - type: load_1m
    - type: load_5m
    - type: load_15m
    - type: processor_use
    - type: processor_temperature

- platform: rest
  name: pws_forecast
  json_attributes:
    - calendarDayTemperatureMax
    - calendarDayTemperatureMin
    - dayOfWeek
    - expirationTimeUtc
    - moonPhase
    - moonPhaseCode
    - moonPhaseDay
    - moonriseTimeLocal
    - moonriseTimeUtc
    - moonsetTimeLocal
    - moonsetTimeUtc
    - narrative
    - qpf
    - qpfSnow
    - sunriseTimeLocal
    - sunriseTimeUtc
    - sunsetTimeLocal
    - sunsetTimeUtc
    - temperatureMax
    - temperatureMin
    - validTimeLocal
    - validTimeUtc
    - daypart
  value_template: '{{ value_json["validTimeLocal"][0] }}'
  resource: !secret wu_forecast_url
  scan_interval: 03:00:00
```

The `- platform: xxxxx` lines generate a `Property platform is not allowed.` error.
The `resources: xxxxx` lines generate a `Property resources not allowed.` error.
The `json_attributes: xxxxx` lines generate a `Property json_attributes not allowed.` error.
The `name: xxxxx` lines generate a `Property name not allowed.` error.
etc.

## Proposed changes

> SCS should not display errors for valid code.
