### ISSUE TITLE
influxdb sensor shows problem, but HA does not

### ISSUE THREAD

**Issue by fribse** [hassio-addons/addon-vscode#399]
# Problem/Motivation

My influxdb sensors shows errors, but Home Assistant does not when checking config

## Expected behavior

No problems should be reported

## Actual behavior

The sensor:

```
- platform: influxdb
  host: localhost
  database: homeassistant
  username: !secret ha-influx-user
  password: !secret ha-influx-pw
  queries:
    - name: UDMP Download Speed
      where: '"subsystem" = ''wan'''
      field: '"rx_bytes-r"'
      measurement: '"subsystems"'
      group_function: last
      database: unifi
      unit_of_measurement: "Mbit/s"
      value_template: "{{ (value | int / 131072) | round(2) }}"
    - name: UDMP Upload Speed
      where: '"subsystem" = ''wan'''
      field: '"tx_bytes-r"'
      measurement: '"subsystems"'
      group_function: last
      database: unifi
      unit_of_measurement: "Mbit/s"
      value_template: "{{ (value | int / 131072) | round(2) }}"
    - name: WAN IP
      where: '"subsystem" = ''wan'''
      field: '"wan_ip"'
      measurement: '"subsystems"'
      group_function: last
      database: unifi
    - name: UDMP CPU
      where: '"subsystem" = ''wan'''
      field: '"gw_cpu"'
      measurement: '"subsystems"'
      group_function: last
      database: unifi
      unit_of_measurement: "%"
    - name: UDMP Memory
      where: '"subsystem" = ''wan'''
      field: '"gw_mem"'
      measurement: '"subsystems"'
      group_function: last
      database: unifi
      unit_of_measurement: "%"
    - name: PM25
      where: "time > now() - 1d"
      field: "SDS_P2"
      group_function: last
      database: luftdaten
      measurement: "feinstaub"
      unit_of_measurement: "ppm"
    - name: PM10
      where: "time > now() - 1d"
      field: "SDS_P1"
      group_function: last
      database: luftdaten
      measurement: "feinstaub"
      unit_of_measurement: "ppm"
```
shows problems for the top of the sensor definition:
![billede](https://user-images.githubusercontent.com/13660621/157817916-f206d180-64b7-4930-aa3d-82e0cd463732.png)
