### ISSUE TITLE
Showing error for the valid code : webostv.turn_on

### ISSUE THREAD

**Issue by satyambaba** [hassio-addons/addon-vscode#445]
# Problem/Motivation

Showing error even if the code is valid and suggested on the [webostv integration page](https://www.home-assistant.io/integrations/webostv/)

## Expected behavior

No error should be shown

## Actual behavior

![Screenshot 2022-05-09 231935](https://user-images.githubusercontent.com/6833101/167468085-d1985da5-9dad-4491-a430-56ef45111743.jpg)

## Steps to reproduce

Just write the automation code below - 
```yaml
- id: webostv_on
  alias: LG WebOS TV On
  mode: single
  trigger:
    - platform: webostv.turn_on
      entity_id: media_player.living_room_tv_3
  action:
    - service: wake_on_lan.send_magic_packet
      data:
        mac: xx:xx:xx:xx:xx:xx
        broadcast_address: xxx.xxx.xxx.x
```
## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)
