### ISSUE TITLE
Show error in ESPHome IR remote yaml files

### ISSUE THREAD

**Issue by AleksandrBraun** [hassio-addons/addon-vscode#461]
# Problem/Motivation
Shows an error, despite the fact that the code is correct and works properly.
> (Why the issue was filed)
After a few updates back.
## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce
Not produced. Waiting for a new update with a fix. But since there is no fix, I understand that not everyone noticed this error.
> (How can someone else make/see it happen)
The error appears in the yaml file with the IR remote set-top box code.
## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

```
  services:
    - service: send_lg_command
      variables:
        command: int[]
      then:
        - remote_transmitter.transmit_raw:
            code: !lambda 'return command;'            Unresolved  tag: !lambda
            carrier_frequency: 38kHz
```

![Screenshot 2022-05-31 at 10-35-15 Studio Code Server – Home Assistant](https://user-images.githubusercontent.com/36089626/171118549-641df0d0-0d18-4f24-b4a7-d6cf72618ae6.png)
