### ISSUE TITLE
False error indications in scripts.yaml

### ISSUE THREAD

**Issue by bdnstn** [hassio-addons/addon-vscode#475]
# Problem/Motivation
When writing a script in VSCode, errors are reported (with red underline) when the script is valid.

## Expected behavior
I expect errors only to be indicated when the syntax is incorrect.

## Steps to reproduce
This script (copied from the yaml under the Scripts tool in HA) works as expected:
```
alias: Demo for each loop
mode: restart
sequence:
  - alias: use a for each loop
    repeat:
      for_each:
        - lounge_lights
        - kitchen_lights
      sequence:
        - service: light.turn_off
          target:
            entity_id: light.{{ repeat.item }}

```

When viewed in VSCode errors are indicated:

![image](https://user-images.githubusercontent.com/24848173/179347236-9555e34d-514f-4843-9b80-c8b6f36e2a03.png)

Since the script executes as expected, I conclude that the error is in VSCode.
