### ISSUE TITLE
Error checking for platform: webostv

### ISSUE THREAD

**Issue by TheRealBenForce** [hassio-addons/addon-vscode#509]
# Problem/Motivation

False error is reported. 
Using version 5.4.0

## Expected behavior

webostv is recognized as a valid platform and no error is reported

## Actual behavior
webostv platform is reported as an error.
![image](https://user-images.githubusercontent.com/8939575/194769546-adb546d2-5d2b-4647-bc31-ae50bbc161ac.png)

Checking the configuration file syntax reports no errors.
![image](https://user-images.githubusercontent.com/8939575/194769625-37d84314-521b-40b8-a60b-6cd33fc7ea87.png)

Automation works as expected. TV can be turned on using the buttons that show after creating the automation:
![image](https://user-images.githubusercontent.com/8939575/194769747-10430a92-dbaa-4832-ab46-ce095f4511e5.png)

## Steps to reproduce

Add the LG WebOS TV Integration
Create an automation like the following:

```
- alias: TV Turned On - Living Room
  description: ""
  mode: single
  trigger:
    - platform: webostv.turn_on
      entity_id: media_player.living_room_tv
  condition: []
  action:
    - service: wake_on_lan.send_magic_packet
      data:
        mac: !secret mac_living_room_tv
        broadcast_address: !secret ip_living_room_tv
```

## Proposed changes

Whatever is needed to make this go away.

Workaround: I believe if you use a device platform such as [in this blueprint](https://community.home-assistant.io/t/lg-webos-smart-tv-enable-turn-on-action-for-ha-2022-2/388153), it works fine. But automations added through the UI can't reference secrets.
