### ISSUE TITLE
device_class: water not accepted by linter?

### ISSUE THREAD

**Issue by saschaludwig** [hassio-addons/addon-vscode#527]
# Problem/Motivation

add a water meter to your configuration yaml 

## Expected behaviour

linter will not complain about device_type: water

## Actual behaviour

linter will complain about device_type:
![Bildschirmfoto 2022-11-09 um 19 22 10](https://user-images.githubusercontent.com/12997980/200910461-e6048e9c-87c2-441e-9ed4-b6f5189537d0.png)

## Steps to reproduce
add this to your configuration.yaml like stated here: https://github.com/home-assistant/home-assistant.io/issues/24801

```
mqtt:
  sensor:
    # Wasserzaehler
    - name: "Wasserzähler"
      state_topic: "wasserzaehler/main/json"
      value_template: "{{ value_json.value }}"
      unit_of_measurement: "m³"
      state_class: "total_increasing"
      icon: "mdi:water"
      unique_id: "wasserzaehler"
      device_class: water

```
