### ISSUE TITLE
state-selector is giving a false positive yaml-schema error

### ISSUE THREAD

**Issue by Grumblezz** [hassio-addons/addon-vscode#886]
# Problem/Motivation

With the update to 2024.10 the syntax of many things are updated, but the following one seems to be a false positive:
![image](https://github.com/user-attachments/assets/8609c655-f2a5-469b-bfb8-56cc8df2e9f9)

In my scripts.yaml:
```
state_test:
  alias: State Test
  sequence: []
  fields:
    entity_state:
      selector:
        state:
          entity_id: update.home_assistant_core_update
      name: Entity State
      default: 'off'
  description: ''
```
The validation error is showing 2 false errors:

`Missing property "action"`
`Property state is not allowed.`

When reviewing the https://www.home-assistant.io/docs/blueprint/selectors/#state-selector then it looks OK. And when I create a new script via the UI with the state selector then the errors are also shown in the VSCode addon.

## Expected behavior

The current selector example should not show a yaml-schema error.

## Actual behavior

The current selector example is showing a yaml-schema error.

## Steps to reproduce

Use the example from above to get the same yaml-schema error.

## Proposed changes

Please fix the yaml-schema error.
