### ISSUE TITLE
Auto-complete in template blocks?

### ISSUE THREAD

**Issue by jasonmadigan** [hassio-addons/addon-vscode#907]
# Problem/Motivation

The HA VS Code Add-on used to provide auto-completion for keywords within template blocks. This hasn't been working now for me for some time, and can't recall when it last worked (couple of months ago?). Entity IDs are auto completed elsewhere in editor, but not in blocks.

For example, typing:

`sensor.ket`

shows matches for `sensor.kettle` if it were filled in in say, the name, unique_id fields. It is not auto-completing in the below multi-line `state` block below however.

```yaml
sensor:
  - name: unaccounted_power
    unique_id: unaccounted_power
    unit_of_measurement: "W"
    device_class: power
    state_class: measurement
    state: >-
      {{
        (
        states('sensor.deye_sunsynk_sol_ark_load_power')|float(0)
        - states('sensor.garage_network_tasmota_energy_power')|float(0)
        - states('sensor.washing_machine_current_consumption')|float(0)
        - states('sensor.dryer_current_consumption')|float(0)
        - states('sensor.plug_desktop_current_consumption')|float(0)
        - states('sensor.office_network_energy_power')|float(0)
        - states('sensor.plug__office_laptop_current_consumption')|float(0)
        - states('sensor.kettle')|float(0)
```

I read https://github.com/hassio-addons/addon-vscode/issues/770 which looked similar, but I see that was resolved some time ago. I am running the latest addon (`5.17.3`).

## Expected behavior

Auto completion of entity IDs within template blocks

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)
