### ISSUE TITLE
state-selector is giving a false positive yaml-schema error

### ISSUE THREAD

**Issue by Grumblezz** [hassio-addons/addon-vscode#932]
Adding a state selector (see: https://www.home-assistant.io/docs/blueprint/selectors/#state-selector ) is shows as a `Missing property "action"` and as a `Property state is not allowed`:
 
![Image](https://github.com/user-attachments/assets/6fd00bd9-e281-4a39-a760-34f49244ff05)

## Steps to reproduce

1. Create a new script with the following content:

```
state_test:
  sequence: []
  fields:
    entity_state:
      selector:
        state:
          entity_id: update.home_assistant_core_update
      name: Entity State
      default: 'on'
      required: true
  alias: State Test
  description: ''
```

![Image](https://github.com/user-attachments/assets/0186fd10-3d20-4c37-a665-f3ef7c25bc93)

2. Go to the Studio Code Server
3. Open the script.yaml and notice that it shows an errors/warning when this type of selector is being used.
![Image](https://github.com/user-attachments/assets/6fd00bd9-e281-4a39-a760-34f49244ff05)

## Expected behaviour
The error/warning should not be shown as I've used the UI to create these selector fields which are inline with the documentation: https://www.home-assistant.io/docs/blueprint/selectors/#state-selector
