### ISSUE TITLE
Config check flags template triggers as an error.

### ISSUE THREAD

**Issue by Mikefila** [hassio-addons/addon-vscode#981]
When defining a template entity in yaml, triggers is flagged as shown below

![Image](https://github.com/user-attachments/assets/500c9468-56ff-4e12-86e5-cb2412e8e410)

This is the example from the [docs](https://www.home-assistant.io/integrations/template/#trigger-based-template-binary-sensors-images-lights-numbers-selects-sensors-switches-and-weathers). It will pass HA's configuration checker and load as expected.

```
template:
  - triggers:
      - trigger: time_pattern
        # This will update every night
        hours: 0
        minutes: 0
    sensor:
      # Keep track how many days have past since a date
      - name: "Not smoking"
        state: '{{ ( ( as_timestamp(now()) - as_timestamp(strptime("06.07.2018", "%d.%m.%Y")) ) / 86400 ) | round(default=0) }}'
        unit_of_measurement: "Days"
```
Studio code server version 5.19.3
